version: '3.6'
services:
  nginx:
    image: nginx:1.18
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - ./src:/var/www/html:rw,cached
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    restart: always

    website:
    image: php:8.0-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - 5000:80
      
  composer:
    image: composer
    container_name: composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
