version: '3.6'
services:

  website:
    image: php:8.0-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - 5000:80
      
  composer:
    image: composer
    container_name: composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
